#!/usr/bin/env python

import json
import logging
import os
import sys

from fritter.config import load_config
from fritter.fritter_service import FritterService

if len(sys.argv) != 2:
    exit("Usage {0} EVENT_FILE.json".format(sys.argv[0]))

logging.basicConfig(level=logging.INFO, stream=sys.stdout)

config = load_config(os.path.dirname(__file__))

fritter = FritterService.create(config)

with open(sys.argv[1]) as f:
    event = json.load(f)
    fritter.event_handler(event)
