#!/usr/bin/env python

try:
    # python 2
    import ConfigParser as configparser
except ImportError:
    # python 3
    import configparser

import json
import logging
import os
import sys

from fritter.fritter_service import FritterService

if len(sys.argv) != 2:
    exit("Usage {0} EVENT_FILE.json".format(sys.argv[0]))

logging.basicConfig(level=logging.INFO, stream=sys.stdout)

baseDir = os.path.dirname(__file__)

config = configparser.SafeConfigParser()
config.readfp(open(os.path.join(baseDir, 'config.ini')))
config.read([os.path.join(baseDir, 'local.ini')])

fritter = FritterService.create(config)

with open(sys.argv[1]) as f:
    event = json.load(f)
    fritter.event_handler(event)
