#!/usr/bin/env python

import logging
import os.path
import sys

from fritter.config import load_config
from fritter.fritter_service import FritterService
from fritter.libfritter.libfritter.sqlitewrapper import PendingSend

logging.basicConfig(level=logging.WARN, stream=sys.stdout)

config = load_config(os.path.dirname(__file__))

mailer, db_connector = FritterService.create_mailer(config)

unsent_mails = PendingSend.Unsent(db_connector, max_results = 50)
for ps in unsent_mails:
    mailer.try_send(ps)
