#!/usr/bin/env python

import logging
import os.path
import sys

from fritter.config import load_config
from fritter.fritter_service import FritterService
from fritter.gerrit_stream.gerritthread import GerritThread

logging.basicConfig(level=logging.INFO, stream=sys.stdout)

config = load_config(os.path.dirname(__file__))

fritter = FritterService.create(config)

listener = GerritThread(config, fritter.event_handler)
listener.daemon = daemon = sys.stdin.isatty()
listener.start()

while daemon:
    try:
        line = sys.stdin.readline()
    except KeyboardInterrupt:
        break
