#!/usr/bin/env python

try:
    # python 2
    import ConfigParser as configparser
except ImportError:
    # python 3
    import configparser

import logging
import os
import sys

from fritter.fritter_service import FritterService
from fritter.libfritter.libfritter.sqlitewrapper import PendingSend

logging.basicConfig(level=logging.INFO, stream=sys.stdout)

baseDir = os.path.dirname(__file__)

config = configparser.SafeConfigParser()
config.readfp(open(os.path.join(baseDir, 'config.ini')))
config.read([os.path.join(baseDir, 'local.ini')])

mailer, db_connector = FritterService.create_mailer(config)

unsent_mails = PendingSend.Unsent(db_connector, max_results = 50)
for ps in unsent_mails:
    mailer.try_send(ps)
