#!/usr/bin/env python

try:
    # python 2
    import ConfigParser as configparser
except ImportError:
    # python 3
    import configparser

import logging
import os
import sys

from fritter.fritter_service import FritterService
from fritter.gerrit_stream.gerritthread import GerritThread

logging.basicConfig(level=logging.INFO, stream=sys.stdout)

baseDir = os.path.dirname(__file__)

config = configparser.SafeConfigParser()
config.readfp(open(os.path.join(baseDir, 'config.ini')))
config.read([os.path.join(baseDir, 'local.ini')])

fritter = FritterService.create(config)

listener = GerritThread(config, fritter.event_handler)
listener.start()

while True:
    try:
        line = sys.stdin.readline()
    except KeyboardInterrupt:
        break
