#!/usr/bin/env python

from __future__ import print_function

import os.path
import sys

if len(sys.argv) != 3:
    exit("Usage {0} REPO REVISION".format(sys.argv[0]))

REPO_ROOT = sys.argv[1]
REVISION = sys.argv[2]

if not os.path.exists(REPO_ROOT):
    exit("Specified repository doesn't exist")

from fritter.config import load_config
from fritter.fritter_service import FritterService
from fritter.repo_template_loader import RepoTemplateLoader

config = load_config(os.path.dirname(__file__))
config.set('fritter', 'project_path', REPO_ROOT)
previewer, lister = FritterService.create_previewer(config, sys.stdout)

files = lister.get_files(REVISION)

for file_path in files:
    print()
    print('-' * 10, file_path, '-' * 10)
    print()
    template_name = RepoTemplateLoader.template_name(file_path, REVISION)
    previewer.preview(template_name)
