#!/usr/bin/env python

from __future__ import print_function

import argparse
import os.path
import sys

parser = argparse.ArgumentParser()
parser.add_argument("repo",
                    help="The repository within which the target revision exists.")
parser.add_argument("revision",
                    help="The revision to preview.")
args = parser.parse_args()
REPO_ROOT = args.repo
REVISION = args.revision

if not os.path.exists(REPO_ROOT):
    exit("Specified repository doesn't exist")

from fritter.config import load_config
from fritter.fritter_service import FritterService
from fritter.repo_template_loader import RepoTemplateLoader

config = load_config(os.path.dirname(__file__))
config.set('fritter', 'project_path', REPO_ROOT)
previewer, lister = FritterService.create_previewer(config, sys.stdout)

files = lister.get_files(REVISION)

for file_path in files:
    print()
    print('-' * 10, file_path, '-' * 10)
    print()
    template_name = RepoTemplateLoader.template_name(file_path, REVISION)
    previewer.preview(template_name)
